[package]
name = "papertrail-downloader"
version = "0.1.0"
description = "Papertrail parallel log archives downloader"
authors = ["ndelvalle <nicolas.delvalle@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/ndelvalle/papertrail-downloader"
repository = "https://github.com/ndelvalle/papertrail-downloader"

[dependencies]
chrono = "0.4.19"
clap = "2.33.3"
futures = "0.3.12"
tokio = { version = "0.2.22", features = ["macros", "fs"] }
reqwest = { version = "0.11.0", features = ["stream"] }
shellexpand = "2.1.0"
indicatif = "0.15.0"
